### ISSUE TITLE
USRBG

### ISSUE THREAD

**Issue by dav1312** [LuckFire/midnight-mars#2]
Right now the USRBG is streched to all of the user popout
![image](https://user-images.githubusercontent.com/63931154/115146030-26e2e380-a055-11eb-97fa-f21c9f6030ac.png)

This would look better so it's only at the top
![image](https://user-images.githubusercontent.com/63931154/115146053-41b55800-a055-11eb-8f7e-97c5cb4a1c23.png)

Also keep in mind that BDFDB now imports the database so doing it in the theme is not necesary anymore for BetterDiscord

```css
.userPopout-3XzG_A .header-2BwW8b {transform: translateZ(0)}
.userPopout-3XzG_A .wrapper-3t9DeA::after {
    content: "";
    position: fixed;
    top: 0 !important;
    left: 0 !important;
    width: 100%;
    height: 100%;
    z-index: -1;
    pointer-events: none;
    opacity: .5;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: var(--user-popout-position) center;
    background-image: var(--user-background);
}
```
